### ISSUE TITLE
install guide or execute guide

### ISSUE THREAD

**Issue by jcyh0120** [damianomagrini/r360-font-converter#1]
Could you provide a guid on how to install this cli?

I clone this repo and run 
`npm install` 
then 
`node index.js -f ./xx.fnt -t ./xx.png > xx.js`

 but got following error.

`
r360-font-converter/node_modules/bmfont2json/index.js:49
            throw "malformed XML/TXT bitmap font file";
            ^
malformed XML/TXT bitmap font file
`

I get my fnt file and png from here.
https://github.com/facebook/react-360/tree/master/OVRUI/fonts

**Comment by jcyh0120** [comment]
I have success importing part of the font. However, I got three loadFont.js file named
loadFont-0
loadFont-1
loadFont-2

How can I concat them together when doing import?
`
import loadFont from './LoadFont-0';
import loadFont1 from './LoadFont-1';
import loadFont2 from './LoadFont-2';
///
r360.runtime.guiSys.font = loadFont();
`
This can only show part of the fonts.

**Comment by DamianoMagrini** [comment]
Sorry for the time it took for me to respond. The fonts from the React360 repo are in a half-converted state (they are in JSON format, but the images are not embedded), and this tool currently doesn't support this format – support should be quite easy to implement though.

For your second issue, I'm not sure whether it is possible to load multiple fonts in React360. I'll look into that.

*EDIT:* also yes I will improve the readme

**Comment by DamianoMagrini** [comment]
Should be fixed in 1.1.0
